### ISSUE TITLE
Mention correcte de l'auteur

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/CartoBio-API#1]
Hello ! Bravo d'avoir une `LICENSE` dans votre premier commit :)

La licence indique "Entrepreneur d'intérêt général" comme auteur pour le dépôt.

La bonne pratique est d'indiquer l'agence dont vous dépendez ("Agence française pour le développement et la promotion de l’agriculture biologique") et vos noms après, à la fois dans le fichier `LICENSE` et quelque part dans le `README.md`.

Si vous avez besoin d'aide sur ces sujets ou si vous préférez que je fasse une PR, n'hésitez pas à me dire.  @AntoineAugusti pourra aussi aider.

**Comment by AntoineAugusti** [comment]
Hello,

En complément, et quand votre projet sera plus avancé, il y a beaucoup de conseils sur cette page https://github.com/entrepreneur-interet-general/eig-link/blob/master/opensource.md. Dispo pour aider.
